### ISSUE TITLE
{{ X }} did not convert to backticks correctly?

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene-jira-archive#70]
I'm not sure what happened here but if you look a [this converted issue](https://github.com/mikemccand/stargazers-migration-test/issues/959), the \`MergePolicy.findFullFlushMerges\` somehow did not properly backtick?  It renders correctly in the corresponding Jira as code.

**Comment by mocobeta** [comment]
`{{X}}` is correctly converted to backticks here. The problem is that the original text in Jira data includes escaping character `\\` before `{{X}}` for some reason, and then it seems GitHub "properly" escapes backticks.
![Screenshot from 2022-07-24 11-40-42](https://user-images.githubusercontent.com/1825333/180629870-d09a678f-bd12-47ab-9037-be1c85818c54.png)

**Comment by mikemccand** [comment]
OK weird but this is likely rare so let's do nothing?

**Comment by mikemccand** [comment]
Thanks for explaining it @mocobeta.
